MPESA_CONSUMER_KEY: 'RfqDHYVDbtAyM31p0o1XJoMdtGrQxRpQzxoAGAJ07tublVBk'
MPESA_CONSUMER_SECRET: 'axcsqZ3G0up1bYArba2vmlO7ss4N0tkCsn7KRFHj53GjtZWnEseDIGR8GzcvYh25'
MPESA_SHORTCODE: '174379'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_INITIATOR_USERNAME: 'nahla-api'
MPESA_INITIATOR_SECURITY_CREDENTIAL: 'Safaricom999!*!'
CALLBACK_URL: 'https://3199-41-139-192-167.ngrok-free.app'
REGISTER_URL: 'https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl'
QUERY_URL: 'https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query'